lcd.c
freq
unsigned char* ARRAY_PORT_PINCFG0
Referenced by init_spi_lcd.
unsigned char* ARRAY_PORT_PMUX0
Referenced by init_spi_lcd.
char dsp_buff_1[17][17]
Referenced by update_lcd_dog, clr_dsp_buff.
char dsp_buff_2[17][17]
Referenced by update_lcd_dog, clr_dsp_buff.
char dsp_buff_3[17][17]
Referenced by update_lcd_dog, clr_dsp_buff.
void delay_30us(void)
References freq.
Referenced by delay_40ms, init_lcd_dog, update_lcd_dog, v_delay.
void v_delay(signed char inner, signed char outer)
References delay_30us, v_delay.
Referenced by v_delay.
void delay_40ms(void)
References delay_30us.
Referenced by init_lcd_dog.
void init_spi_lcd(void)
References ARRAY_PORT_PINCFG0, ARRAY_PORT_PMUX0.
Referenced by init_lcd_dog, update_lcd_dog.
void lcd_spi_transmit_CMD(char CMD)
Referenced by init_lcd_dog, update_lcd_dog.
void lcd_spi_transmit_DATA(char data)
Referenced by update_lcd_dog.
void init_lcd_dog(void)
References delay_30us, delay_40ms, init_spi_lcd, lcd_spi_transmit_CMD.
Referenced by main.
void update_lcd_dog(void)
References delay_30us, dsp_buff_1, dsp_buff_2, dsp_buff_3, init_spi_lcd, lcd_spi_transmit_CMD, lcd_spi_transmit_DATA.
Referenced by clr_dsp_buff.
void clr_dsp_buff(void)
References dsp_buff_1, dsp_buff_2, dsp_buff_3, update_lcd_dog.