.TH "//Mac/Home/Desktop/ESE 381/Labs/Lab 10/lab10_task1/lab10_task1 Directory Reference" 3 "Mon May 11 2020" "Lab10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
//Mac/Home/Desktop/ESE 381/Labs/Lab 10/lab10_task1/lab10_task1 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbme680\&.c\fP"
.br
.RI "Sensor driver for BME680 sensor\&. "
.ti -1c
.RI "file \fBbme680\&.h\fP"
.br
.RI "Sensor driver for BME680 sensor\&. "
.ti -1c
.RI "file \fBbme680_defs\&.h\fP"
.br
.RI "Sensor driver for BME680 sensor\&. "
.ti -1c
.RI "file \fBlcd\&.c\fP"
.br
.ti -1c
.RI "file \fBlcd\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBrs232\&.c\fP"
.br
.ti -1c
.RI "file \fBrs232\&.h\fP"
.br
.ti -1c
.RI "file \fBsys_support\&.c\fP"
.br
.ti -1c
.RI "file \fBsys_support\&.h\fP"
.br
.in -1c
