.TH "bme680_gas_sett" 3 "Mon May 11 2020" "Lab10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bme680_gas_sett \- BME680 gas sensor which comprises of gas settings and status parameters\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bme680_defs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBnb_conv\fP"
.br
.ti -1c
.RI "uint8_t \fBheatr_ctrl\fP"
.br
.ti -1c
.RI "uint8_t \fBrun_gas\fP"
.br
.ti -1c
.RI "uint16_t \fBheatr_temp\fP"
.br
.ti -1c
.RI "uint16_t \fBheatr_dur\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
BME680 gas sensor which comprises of gas settings and status parameters\&. 
.PP
Definition at line 492 of file bme680_defs\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t heatr_ctrl"
Variable to store heater control 
.PP
Definition at line 496 of file bme680_defs\&.h\&.
.SS "uint16_t heatr_dur"
Duration profile value 
.PP
Definition at line 502 of file bme680_defs\&.h\&.
.SS "uint16_t heatr_temp"
Heater temperature value 
.PP
Definition at line 500 of file bme680_defs\&.h\&.
.SS "uint8_t nb_conv"
Variable to store nb conversion 
.PP
Definition at line 494 of file bme680_defs\&.h\&.
.SS "uint8_t run_gas"
Run gas enable value 
.PP
Definition at line 498 of file bme680_defs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab10 from the source code\&.
