.TH "bme680_field_data" 3 "Mon May 11 2020" "Lab10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bme680_field_data \- Sensor field data structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bme680_defs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBstatus\fP"
.br
.ti -1c
.RI "uint8_t \fBgas_index\fP"
.br
.ti -1c
.RI "uint8_t \fBmeas_index\fP"
.br
.ti -1c
.RI "int16_t \fBtemperature\fP"
.br
.ti -1c
.RI "uint32_t \fBpressure\fP"
.br
.ti -1c
.RI "uint32_t \fBhumidity\fP"
.br
.ti -1c
.RI "uint32_t \fBgas_resistance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Sensor field data structure\&. 
.PP
Definition at line 376 of file bme680_defs\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t gas_index"
The index of the heater profile used 
.PP
Definition at line 380 of file bme680_defs\&.h\&.
.SS "uint32_t gas_resistance"
Gas resistance in Ohms 
.PP
Definition at line 392 of file bme680_defs\&.h\&.
.SS "uint32_t humidity"
Humidity in % relative humidity x1000 
.PP
Definition at line 390 of file bme680_defs\&.h\&.
.SS "uint8_t meas_index"
Measurement index to track order 
.PP
Definition at line 382 of file bme680_defs\&.h\&.
.SS "uint32_t pressure"
Pressure in Pascal 
.PP
Definition at line 388 of file bme680_defs\&.h\&.
.SS "uint8_t status"
Contains new_data, gasm_valid & heat_stab 
.PP
Definition at line 378 of file bme680_defs\&.h\&.
.SS "int16_t temperature"
Temperature in degree celsius x100 
.PP
Definition at line 386 of file bme680_defs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab10 from the source code\&.
