.TH "//Mac/Home/Desktop/ESE 381/Labs/Lab 10/lab10_task1/lab10_task1/sys_support.h" 3 "Mon May 11 2020" "Lab10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
//Mac/Home/Desktop/ESE 381/Labs/Lab 10/lab10_task1/lab10_task1/sys_support.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fB_write\fP (FILE *f, char *buf, int n)"
.br
.ti -1c
.RI "int \fB_read\fP (FILE *f, char *buf, int n)"
.br
.ti -1c
.RI "int \fB_close\fP (FILE *f)"
.br
.ti -1c
.RI "int \fB_fstat\fP (FILE *f, void *p)"
.br
.ti -1c
.RI "int \fB_isatty\fP (FILE *f)"
.br
.ti -1c
.RI "int \fB_lseek\fP (FILE *f, int o, int w)"
.br
.ti -1c
.RI "void * \fB_sbrk\fP (int i)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int _close (FILE * f)"

.PP
Definition at line 39 of file sys_support\&.c\&.
.SS "int _fstat (FILE * f, void * p)"

.PP
Definition at line 43 of file sys_support\&.c\&.
.SS "int _isatty (FILE * f)"

.PP
Definition at line 48 of file sys_support\&.c\&.
.SS "int _lseek (FILE * f, int o, int w)"

.PP
Definition at line 52 of file sys_support\&.c\&.
.SS "int _read (FILE * f, char * buf, int n)"

.PP
Definition at line 29 of file sys_support\&.c\&.
.SS "void* _sbrk (int i)"

.PP
Definition at line 56 of file sys_support\&.c\&.
.SS "int _write (FILE * f, char * buf, int n)"

.PP
Definition at line 22 of file sys_support\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab10 from the source code\&.
